const menu = [
  {
    id: 1,
    title: "masala Chai",
    category: "Beverages",
    fullPrice: "₹15/- cup",
    img: "https://carameltintedlife.com/wp-content/uploads/2021/01/Masala-Chai-.jpg",
  },
  {
    id: 2,
    title: "hot coffee",
    category: "Beverages",
    fullPrice: "₹30/- cup",
    img: "https://getwallpapers.com/wallpaper/full/a/8/4/1040113-free-coffee-cup-wallpaper-2560x1600-for-ipad.jpg",
  },
  {
    id: 3,
    title: "chole/rajma chawal",
    category: "Lunch",
    fullPrice: "₹60/- plate",
    img: "https://i.pinimg.com/474x/40/7d/dd/407ddd677e8785a9e92ae26460cc7829.jpg",
  },
  {
    id: 4,
    title: "chilli potato",
    category: "Chinese",
    fullPrice: "₹90 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg",
  },
  {
    id: 5,
    title: "honey chilli potato",
    category: "Chinese",
    fullPrice: "₹100 (Full)",
    halfPrice: "₹60 (Half)",
    img: "https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg",
  },
  {
    id: 6,
    title: "french fries",
    category: "Chinese",
    fullPrice: "₹80 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://c.ndtvimg.com/2020-06/m7ngt6ho_french-fries_625x300_18_June_20.jpg",
  },
  {
    id: 7,
    title: "peri peri french fries",
    category: "Chinese",
    fullPrice: "₹90 (Full)",
    halfPrice: "₹60 (Half)",
    img: "https://c.ndtvimg.com/2020-06/m7ngt6ho_french-fries_625x300_18_June_20.jpg",
  },
  {
    id: 8,
    title: "cheesy potato stick",
    category: "Chinese",
    fullPrice: "₹80 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://aartimadan.com/wp-content/uploads/2023/04/Cheesy-Potato-Bread-Sticks.jpg",
  },
  {
    id: 9,
    title: "paneer momos (steam)",
    category: "Chinese",
    fullPrice: "₹60 (10pcs.)",
    halfPrice: "₹35 (5pcs.)",
    img: "https://timesrecipe.com/wp-content/uploads/2022/04/How-To-Make-Paneer-Momos-in-Hindi-Timesrecipe.com_.webp",
  },
  {
    id: 10,
    title: "paneer momos (fried)",
    category: "Chinese",
    fullPrice: "₹70 (10pcs.)",
    halfPrice: "₹40 (5pcs.)",
    img: "https://i.pinimg.com/originals/86/08/d1/8608d13519df60695bbac90b899be26b.jpg",
  },
  {
    id: 11,
    title: "veg momos (steam)",
    category: "Chinese",
    fullPrice: "₹50 (10pcs.)",
    halfPrice: "₹30 (5pcs.)",
    img: "https://www.vegrecipesofindia.com/wp-content/uploads/2016/09/whole-wheat-veg-momos-recipe-1.jpg",
  },
  {
    id: 12,
    title: "veg momos (fried)",
    category: "Chinese",
    fullPrice: "₹60 (10pcs.)",
    halfPrice: "₹35 (5pcs.)",
    img: "https://b.zmtcdn.com/data/dish_photos/a22/8da8bb57b47add934d8558014f419a22.jpg",
  },
  {
    id: 13,
    title: "manchurian",
    category: "Chinese",
    fullPrice: "₹80 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://www.licious.in/blog/wp-content/uploads/2021/09/shutterstock_1650877375.jpg",
  },
  {
    id: 14,
    title: "fried rice",
    category: "Chinese",
    fullPrice: "₹80 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://40aprons.com/wp-content/uploads/2022/03/chicken-fried-rice-3.jpg",
  },
  {
    id: 15,
    title: "chowmein",
    category: "Chinese",
    fullPrice: "₹80 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://i.ytimg.com/vi/gbygXUDbf2Q/sddefault.jpg",
  },
  {
    id: 16,
    title: "red sauce pasta",
    category: "Chinese",
    fullPrice: "₹90 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://irhindi.in/wp-content/uploads/2023/03/red-sauce-pasta-recipe.jpg",
  },
  {
    id: 17,
    title: "white sauce pasta",
    category: "Chinese",
    fullPrice: "₹100 (Full)",
    halfPrice: "₹60 (Half)",
    img: "https://www.whiskaffair.com/wp-content/uploads/2021/05/White-Sauce-Paste-2-3.jpg",
  },
  {
    id: 18,
    title: "mix sauce pasta",
    category: "Chinese",
    fullPrice: "₹90 (Full)",
    halfPrice: "₹50 (Half)",
    img: "https://thecozycook.com/wp-content/uploads/2022/07/Pink-Sauce-Pasta-f2.jpg",
  },
  {
    id: 19,
    title: "spring roll",
    category: "Chinese",
    fullPrice: "₹80 (Full)",
    halfPrice: "₹40 (Half)",
    img: "https://www.licious.in/blog/wp-content/uploads/2021/11/Vegetable-Rolls.jpg",
  },
  {
    id: 20,
    title: "chilli paneer",
    category: "Chinese",
    fullPrice: "₹120 (Full)",
    halfPrice: "₹60 (Half)",
    img: "https://rumkisgoldenspoon.com/wp-content/uploads/2021/04/Chilli-paneer-dry.jpg",
  },
  {
    id: 21,
    title: "paneer roll",
    category: "Snacks",
    fullPrice: "₹50",
    img: "https://www.potsandpans.in/cdn/shop/articles/12.jpg?v=1539863851",
  },
  {
    id: 22,
    title: "pasta roll",
    category: "Snacks",
    fullPrice: "₹50",
    img: "https://letsdishrecipes.com/wp-content/uploads/2018/08/Southwest-Chicken-feature2-480x270.jpg",
  },
  {
    id: 23,
    title: "cheese roll",
    category: "Snacks",
    fullPrice: "₹40",
    img: "https://www.melskitchencafe.com/wp-content/uploads/2008/06/crispy-chicken-wraps.jpg",
  },
  {
    id: 24,
    title: "maxican roll",
    category: "Snacks",
    fullPrice: "₹40",
    img: "https://tiffinandteaofficial.com/wp-content/uploads/2020/04/IMG_5905-1-scaled.jpg",
  },
  {
    id: 25,
    title: "maggie",
    category: "Snacks",
    fullPrice: "₹40",
    img: "https://3.bp.blogspot.com/-42ydTiZKNU4/WGXWVFFbj9I/AAAAAAAAAmg/h7MtcbM9EegJ0BFJdvGSUd-2Cr4xg-H1wCLcB/s1600/1-89.jpg",
  },
  {
    id: 26,
    title: "cold drinks",
    category: "Beverages",
    fullPrice: "MRP",
    img: "https://media.istockphoto.com/id/533575209/photo/soft-drink-being-poured-into-glass.jpg?s=612x612&w=0&k=20&c=OPfGgxIkH_6j-ozfWol5RxypTAIZSmkR3NL-qsJ7_Qk=",
  },
  {
    id: 27,
    title: "cold coffee",
    category: "Beverages",
    fullPrice: "₹50",
    img: "https://www.cookwithmanali.com/wp-content/uploads/2022/04/Cold-Coffee.jpg",
  },
  {
    id: 28,
    title: "black current shake",
    category: "Beverages",
    fullPrice: "₹80 (Thick)",
    img: "https://5.imimg.com/data5/ML/OZ/NC/SELLER-39577706/black-current-500x500.jpg",
  },
  {
    id: 29,
    title: "butterscotch shake",
    category: "Beverages",
    fullPrice: "₹80 (Thick)",
    img: "https://tyberrymuch.com/wp-content/uploads/2021/11/butterscotch-milkshake-hero-recipe-735x735.jpg",
  },
  {
    id: 30,
    title: "chocolate shake",
    category: "Beverages",
    fullPrice: "₹80 (Thick)",
    img: "https://www.cambiati.com/wp-content/uploads/2014/03/Chocolate-shake-96907264-scaled.jpeg",
  },
  {
    id: 31,
    title: "pineapple shake",
    category: "Beverages",
    fullPrice: "₹80 (Thick)",
    img: "https://healthytasteoflife.com/wp-content/uploads/2021/05/pineapple-milkshake-dairy-free-1024x1536.jpg",
  },
  {
    id: 32,
    title: "mango shake",
    category: "Beverages",
    fullPrice: "₹80 (Thick)",
    img: "https://www.eastcoastdaily.in/wp-content/uploads/2018/10/mango-milkshake.jpg",
  },
  {
    id: 33,
    title: "oreo shake",
    category: "Beverages",
    fullPrice: "₹80 (Thick)",
    img: "https://www.mojapasjasmaku.pl/wp-content/uploads/2014/06/1-2-.jpg",
  },
  {
    id: 34,
    title: "mango ice-cream",
    category: "IceCream",
    fullPrice: "₹25 (single scoop)",
    img: "https://www.funfoodfrolic.com/wp-content/uploads/2020/04/Mango-Ice-Cream-Thumbnail.jpg",
  },
  {
    id: 35,
    title: "chocolate ice-cream",
    category: "IceCream",
    fullPrice: "₹25 (single scoop)",
    img: "https://ashleemarie.com/wp-content/uploads/2014/02/homemade-chocolate-ice-cream-recipe.jpg",
  },
  {
    id: 36,
    title: "vanilla ice-cream",
    category: "IceCream",
    fullPrice: "₹25 (single scoop)",
    img: "https://thebusybaker.ca/wp-content/uploads/2019/05/best-ever-no-churn-vanilla-ice-cream-fb-ig-2.jpg",
  },
  {
    id: 37,
    title: "butterscotch ice-cream",
    category: "IceCream",
    fullPrice: "₹25 (single scoop)",
    img: "https://images.herzindagi.info/image/2020/Apr/butterscotch-ice-cream-recipe-two.jpg",
  },
  {
    id: 38,
    title: "soup",
    category: "Beverages",
    fullPrice: "₹30/- cup",
    img: "https://i5.walmartimages.com/asr/9bbcdc73-ea3a-4adf-aaef-03969ab6e8b9_1.d34824f73fdc3abacbf32423e7e987f1.jpeg",
  },
  {
    id: 39,
    title: "vegetable gratin",
    category: "Healthy Snacks",
    fullPrice: "₹30/- ",
    img: "https://www.lifeberrys.com/img/article/vegetable-au-gratin-1625249706-lb.jpg",
  },
  {
    id: 40,
    title: "masala oats",
    category: "Healthy Snacks",
    fullPrice: "₹40/- plate",
    img: "https://www.indianveggiedelight.com/wp-content/uploads/2021/05/masala-oats.jpg",
  },
  {
    id: 41,
    title: "soup",
    category: "Healthy Snacks",
    fullPrice: "₹30/- cup",
    img: "https://i5.walmartimages.com/asr/9bbcdc73-ea3a-4adf-aaef-03969ab6e8b9_1.d34824f73fdc3abacbf32423e7e987f1.jpeg",
  },
  {
    id: 42,
    title: "upma",
    category: "Healthy Snacks",
    fullPrice: "₹40/- plate",
    img: "https://fthmb.tqn.com/RPjDuPB78ppY70JBor_7t2DTpdY=/2569x1945/filters:fill(auto,1)/upma-56a510633df78cf772862b9b.jpg",
  },
];

export default menu;
