const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'Breakfast',
    fullPrice: 15.99,
    halfPrice: 15.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 2,
    title: 'diner double',
    category: 'Chinese',
    fullPrice: 13.99,
    halfPrice: 13.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'Snacks',
    fullPrice: 6.99,
    halfPrice: 6.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 4,
    title: 'country delight',
    category: 'Beverages',
    fullPrice: 20.99,
    halfPrice: 20.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'Breakfast',
    fullPrice: 22.99,
    halfPrice: 22.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'Chinese',
    fullPrice: 18.99,
    halfPrice: 18.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'Snacks',
    fullPrice: 8.99,
    halfPrice: 8.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 8,
    title: 'american classic',
    category: 'Beverages',
    fullPrice: 12.99,
    halfPrice: 12.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'Breakfast',
    fullPrice: 16.99,
    halfPrice: 16.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'Chinese',
    fullPrice: 16.99,
    halfPrice: 16.99,
    img: 'https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg',
  },
];
export default menu;
